# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go

on:
  push:
    branches: [ "master", "setup-cicd" ]
  pull_request:
    branches: [ "master", "setup-cicd" ]

jobs:

  build:
    runs-on: ubuntu-latest
    container:
      image: debian:bullseye

    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.24.1'

    - name: Setup dependencies
      run: apt-get update && apt-get install -y gcc libgl1-mesa-dev xorg-dev libxkbcommon-dev make

    - name: Build
      run: make build-linux
